### ISSUE TITLE
关于copy_weight_v6（）函数

### ISSUE THREAD

**Issue by shaotuanjie** [ZJU-lishuang/yolov5-v6#1]
您好，看了您的工程，大佬太厉害了！

有个问题想请教一下. 我训练好一个原始结构模型，然后用copy_weight_v6()生成一个新的模型，但是最后测试发现新生成的模型和原始的模型预测结果差很多，请问可能是什么问题导致的呢。

**Comment by ZJU-lishuang** [comment]
copy_weight_v6函数所在的文件有模型对比，可以调试
